// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cplex_present
SEXP cplex_present();
RcppExport SEXP _transport_cplex_present() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cplex_present());
    return rcpp_result_gen;
END_RCPP
}
// SolveHierarchicalTransport
SEXP SolveHierarchicalTransport(SEXP x, SEXP y, SEXP xydepth, SEXP xydimensions, SEXP compdepth, SEXP measureScaleVecPre, SEXP keepBasisVecPre, SEXP refineBasisVecPre, SEXP layerCoarsestVecPre, SEXP verboseVecPre, SEXP assignment, SEXP udummy, SEXP vdummy);
RcppExport SEXP _transport_SolveHierarchicalTransport(SEXP xSEXP, SEXP ySEXP, SEXP xydepthSEXP, SEXP xydimensionsSEXP, SEXP compdepthSEXP, SEXP measureScaleVecPreSEXP, SEXP keepBasisVecPreSEXP, SEXP refineBasisVecPreSEXP, SEXP layerCoarsestVecPreSEXP, SEXP verboseVecPreSEXP, SEXP assignmentSEXP, SEXP udummySEXP, SEXP vdummySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type xydepth(xydepthSEXP);
    Rcpp::traits::input_parameter< SEXP >::type xydimensions(xydimensionsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type compdepth(compdepthSEXP);
    Rcpp::traits::input_parameter< SEXP >::type measureScaleVecPre(measureScaleVecPreSEXP);
    Rcpp::traits::input_parameter< SEXP >::type keepBasisVecPre(keepBasisVecPreSEXP);
    Rcpp::traits::input_parameter< SEXP >::type refineBasisVecPre(refineBasisVecPreSEXP);
    Rcpp::traits::input_parameter< SEXP >::type layerCoarsestVecPre(layerCoarsestVecPreSEXP);
    Rcpp::traits::input_parameter< SEXP >::type verboseVecPre(verboseVecPreSEXP);
    Rcpp::traits::input_parameter< SEXP >::type assignment(assignmentSEXP);
    Rcpp::traits::input_parameter< SEXP >::type udummy(udummySEXP);
    Rcpp::traits::input_parameter< SEXP >::type vdummy(vdummySEXP);
    rcpp_result_gen = Rcpp::wrap(SolveHierarchicalTransport(x, y, xydepth, xydimensions, compdepth, measureScaleVecPre, keepBasisVecPre, refineBasisVecPre, layerCoarsestVecPre, verboseVecPre, assignment, udummy, vdummy));
    return rcpp_result_gen;
END_RCPP
}
