# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cplex_present <- function() {
    .Call(`_transport_cplex_present`)
}

SolveHierarchicalTransport <- function(x, y, xydepth, xydimensions, compdepth, measureScaleVecPre, keepBasisVecPre, refineBasisVecPre, layerCoarsestVecPre, verboseVecPre, assignment, udummy, vdummy) {
    .Call(`_transport_SolveHierarchicalTransport`, x, y, xydepth, xydimensions, compdepth, measureScaleVecPre, keepBasisVecPre, refineBasisVecPre, layerCoarsestVecPre, verboseVecPre, assignment, udummy, vdummy)
}

